server:
  port: 8081

spring:
  application:
    name: ig-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/inbox}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    show-sql: false
  flyway:
    enabled: ${FLYWAY_ENABLED:false}  # Desactivado por defecto, api-gateway maneja migraciones
    locations: classpath:db/migration
    baseline-on-migrate: true

instagram:
  verify-token: ${IG_VERIFY_TOKEN:demo_token}
  graph-version: ${IG_GRAPH_VERSION:v21.0}
  page-access-token: ${IG_PAGE_ACCESS_TOKEN:}
  user-id: ${IG_USER_ID:}
  graph-api-base-url: https://graph.facebook.com

logging:
  level:
    com.unir: DEBUG
    org.springframework.web: INFO

